### ISSUE TITLE
Run from subdirectory of the repository

### ISSUE THREAD

**Issue by jpschewe** [github/git-sizer#10]
Trying to run from a subdirectory of the git repository doesn't work. In the example here "working-dir" is the top of the repository.
```
>git-sizer 
fatal: Cannot change to 'home/jpschewe/projects/fll-sw/working-dir/.git': No such file or directory
fatal: Cannot change to 'home/jpschewe/projects/fll-sw/working-dir/.git': No such file or directory
fatal: Cannot change to 'home/jpschewe/projects/fll-sw/working-dir/.git': No such file or directory
Processing blobs: 0                        
error: error scanning repository: exit status 128
```

**Comment by mhagger** [comment]
Thanks for the error report. TIL that Go's `path.filepath.Join()` doesn't work the same as Python's `os.path.join()` if the second argument is an absolute path. #16 should fix this problem.

**Comment by leethargo** [comment]
I'm having a related problem with `git submodules`. That is, I have `repoA` which has `repoB` as a submodule. Then, when I `cd` into `repoA/repoB` and run `git-sizer`, I get:
```
fatal: Cannot change to 'home/rs/src/repoA/.git/modules/repoB': No such file or directory
```
