### ISSUE TITLE
Obtain a list of biggest files in the repository.

### ISSUE THREAD

**Issue by CodeMaster7000** [github/git-sizer#101]

**Comment by larsxschneider** [comment]
👋 `git-sizer`'s objective is give you a "one-page" overview of your repository health. Therefore, a "list of the biggest files" is a little out of scope I think.

I highly recommend the https://github.com/newren/git-filter-repo tool for this task, though. If you run `git-filter-repo --analyze`, then you will get lots of detailed information where big files and directories are located in your repository.
