### ISSUE TITLE
Question: is there anyway I can get the count of files in particular language for example cuda statistics 

### ISSUE THREAD

**Issue by learnnshare** [github/git-sizer#102]
Is there any way I can get a count of files in a particular language, for example, cuda statistics in the repository?
My end goal:
Search entire GitHub for repositories that use Cuda, and then sort them by various metrics.
Most popular ; most forks; highest percentage of cuda files etc.
Thank you for taking time to answer my question

**Comment by mhagger** [comment]
No, sorry, that's out of scope for `git-sizer`.
