### ISSUE TITLE
Can it work on a bare repo?

### ISSUE THREAD

**Issue by sriprasannaMG** [github/git-sizer#107]
Hi,
Thanks for this wonderful solution! 
We are thinking to do the analysis directly on the hosting service (Bitbucket). 
As the hosting service contains all the repos as bare repos would it be possible to run the git-sizer on all those bare repos.

Idea would be get the analytics org.wide and based on anomalies found we  can then have a closer look / correction of individual repositories.

Thanks!

**Comment by mhagger** [comment]
Yes, it works fine on a bare repo.
