### ISSUE TITLE
Tab issue in README.md, weird display of a list

### ISSUE THREAD

**Issue by Naereen** [github/git-sizer#14]
See [this part of the README](https://github.com/github/git-sizer/#getting-started):
![gitsizer_ugly_readme](https://user-images.githubusercontent.com/11994719/37027182-e684cfde-2130-11e8-8f4e-26cebe068630.png)
PR will come directly to fix this.

**Comment by mhagger** [comment]
Thanks for noticing this issue; I feel silly for not noticing it myself. This has been fixed via #12.
