### ISSUE TITLE
error: Could not read changeset

### ISSUE THREAD

**Issue by Kaleesastha** [github/git-sizer#27]
When we executed the git-sizer binary for our repo which has 1.8GiB git repository. We got the exception which is given below for your reference : 

```error: Could not read 5a8e42294cb27289b3dc0a1e6753748f34fa2698
fatal: revision walk setup failed
Processing blobs: 0                        
error: error scanning repository: exit status 128
[root@f258e46eaf0a zohobooks_server.git]# 
```

Git version - ```git version 2.15.1```

Kindly help us to resolve the issue.

Thanks,

Kaleeswaran

**Comment by mhagger** [comment]
That problem is generated from within Git itself. It could be a bug in Git or, more likely, corruption in your repository. Try running

    git fsck --no-dangling

to check for corruption. If that doesn't report any problems, try running

    git rev-list --objects --date-order --all | wc -l

, which is an approximation of what `git-sizer` runs (piped to `wc` so that you are not inundated with output).

**Comment by Kaleesastha** [comment]
@mhagger  we got the some output  for git fsck --no-dangling command which is listed below :- 

```
Checking object directories: 100% (256/256), done.
Checking objects: 100% (496047/496047), done.
broken link from  commit 2bdf45df2193bd569d440fb7e495c352b7403f91
              to    tree 4bef4e75656aa9ec1c08dca582f2b09145796688
broken link from  commit d80a9869db7bc5a42344236441a1d085d663332f
              to    tree e21a51d9249481b18f831b2cc3a217f75a737d43
broken link from  commit f72d7affe85fd7296026a826eb6e7079254b21f9
              to    tree 122c30fa7b90f076a55b5cf65d768d207dc4b635
broken link from  commit f72d7affe85fd7296026a826eb6e7079254b21f9
              to  commit 5a8e42294cb27289b3dc0a1e6753748f34fa2698
Checking connectivity: 509742, done.
missing commit 5a8e42294cb27289b3dc0a1e6753748f34fa2698
missing tree 4bef4e75656aa9ec1c08dca582f2b09145796688
missing tree 122c30fa7b90f076a55b5cf65d768d207dc4b635
missing tree e21a51d9249481b18f831b2cc3a217f75a737d43
```

Is it possible to continue further Or I need to fix this above issue.

**Comment by mhagger** [comment]
@Kaleesastha: the `git fsck` output indicates that your repository is corrupt (it is missing objects). You need to fix the corruption.

* It might be that the missing objects are only reachable from reflogs. If so, then

        git reflog expire --stale-fix --expire-unreachable=all --all

    might fix it.

* If you have backups or other copies of the repository (e.g., maybe your co-workers also have clones), you might be able to scavenge the missing objects from there.
* If neither of those work, then it might be that the missing objects are only reachable from some unneeded and/or obsolete references that you could delete.

If none of those work, you might be forced to rewrite history to excise the missing objects. But that is well beyond the scope of `git-sizer`.

Good luck!
