### ISSUE TITLE
Don't show objects that only in Stash

### ISSUE THREAD

**Issue by KindDragon** [github/git-sizer#29]

**Comment by mhagger** [comment]
I'm torn about whether this and #1 should be the *default* behavior or whether they should be options. For example, `--stash`/`--no-stash`, `--notes`/`--no-notes`, and/or even more flexible options like `--include=refs/pull/*`/`--exclude=refs/changes/*`.

Meanwhile, as a workaround, `git sizer --branches --tags --remotes` might be close to what you want.

**Comment by JayAndCatchFire** [comment]
I think that git-sizer should warn about things like those that are uncommitted or things that are stashed.  As @mhagger mentioned in #22, the goal of this project is to detect issues _before_ they'd call for drastic action like a history rewrite.

**Comment by mhagger** [comment]
This can now be accomplished using the new feature `--exclude=refs/stash`, introduced in #75. It could be made more convenient using helper options like `--stash` / `--no-stash` (see #77), but I'll nevertheless mark this wish done for now.
