### ISSUE TITLE
--version flag or similar

### ISSUE THREAD

**Issue by JayAndCatchFire** [github/git-sizer#36]
I just checked in on this project to see if there was a newer release than the one I have in my `~/bin` folder.  I saw there has a second release, but I had no idea which version I had locally.  I mean, I _think_ the latest release was newer than the one I had, but I was surprised to to find that running `git-sizer --version` gave me `unknown flag: --version`.  So I just had to overwrite the binary whether I actually needed to or not.  :man_shrugging:

**Comment by mhagger** [comment]
It is definitely a good idea to add a `--version` option. Is there a standard way of doing that in Go? It should be relatively idiot-proof and also do something sensible for dev builds between official releases.

**Comment by JayAndCatchFire** [comment]
I would assume so, but I don't know Go.  I kind of wish I did so I could offer a pull request.
