### ISSUE TITLE
error: error scanning repository: <commit-id> has no header separator

### ISSUE THREAD

**Issue by gzer0-0ne** [github/git-sizer#41]
I am running git-sizer on https://source.codeaurora.org/quic/qsdk/oss/kernel/linux-msm repository (2.4GB in size) and I get the following error.

error: error scanning repository: e34c586c99f12db9ebf61598a960a27f4e0359cd has no header separator

Line in source 
git.go:578: return ObjectHeaderIter{}, fmt.Errorf("%s has no header separator", name)

I suspect the issue is with the repository and not with the tool. Is there a  way to skip this and still run git-sizer on the repo?

TiA
zer0-0ne

**Comment by mhagger** [comment]
You're very likely correct that this is a problem with the repository. If you want to double-check, you can run `git fsck --no-dangling` against the repository, which will probably report the same sort of corruption.

There is currently no way in `git-sizer` to work around repository corruption. What does that commit actually look like? Try running

    git cat-file commit e34c586c99f12db9ebf61598a960a27f4e0359cd

It it's just missing its commit message, the above code could be tweaked to ignore the problem. If it's really messed up, then maybe you should try to repair your repository first.

**Comment by gzer0-0ne** [comment]
I don't own/maintain the repository.  We have decided to take an alternate approach and won't be working on this repository any more. If you are interested in fixing or providing an option to  ignore these errors, here are the git command the outputs from this repository

$ git cat-file commit e34c586c99f12db9ebf61598a960a27f4e0359cd
tree 0b5e00723e3f8a6512484df46c5445fddbc2e3e3
parent 9cec53cc4d2e70eec32c646148c477350fe9069f
author Adrian Bunk <bunk@stusta.de> 1156539074 +0200
committer Adrian Bunk <bunk@stusta.de> 1156539074 +0200

Linux 2.6.16.28

linux-msm$ git fsck --no-dangling
notice: HEAD points to an unborn branch (master)
Checking object directories: 100% (256/256), done.
warning in tag 5dc01c595e6c6ec9ccda4f6f69c131c0dd945f8c: missingTaggerEntry: invalid format - expected 'tagger' line
warning in tag 26791a8bcf0e6d33f43aef7682bdb555236d56de: missingTaggerEntry: invalid format - expected 'tagger' line
warning in tag 9e734775f7c22d2f89943ad6c745571f1930105f: missingTaggerEntry: invalid format - expected 'tagger' line
warning in tag 0397236d43e48e821cce5bbe6a80a1a56bb7cc3a: missingTaggerEntry: invalid format - expected 'tagger' line
warning in tag ebb5573ea8beaf000d4833735f3e53acb9af844c: missingTaggerEntry: invalid format - expected 'tagger' line
warning in tag 06f6d9e2f140466eeb41e494e14167f90210f89d: missingTaggerEntry: invalid format - expected 'tagger' line
warning in tag 701d7ecec3e0c6b4ab9bb824fd2b34be4da63b7e: missingTaggerEntry: invalid format - expected 'tagger' line
warning in tag 254cc2c3d0745835f73f5c9a76482b691668a738: missingTaggerEntry: invalid format - expected 'tagger' line
warning in tag 279c674f31885b18fd312149e7938850f7bd13bb: missingTaggerEntry: invalid format - expected 'tagger' line
warning in tag ea5a02080269424e629de1e7f1f385ba9be337ba: missingTaggerEntry: invalid format - expected 'tagger' line
warning in tag 733ad933f62e82ebc92fed988c7f0795e64dea62: missingTaggerEntry: invalid format - expected 'tagger' line
warning in tag c521cb0f10ef2bf28a18e1cc8adf378ccbbe5a19: missingTaggerEntry: invalid format - expected 'tagger' line
warning in tag a339981ec18d304f9efeb9ccf01b1f04302edf32: missingTaggerEntry: invalid format - expected 'tagger' line
Checking objects: 100% (12852791/12852791), done.
Checking connectivity: 12852791, done.

**Comment by mhagger** [comment]
I don't see any obvious breakage in that commit. Perhaps the line endings are wrong (e.g., CRLF instead of LF). It's odd that `git fsck` doesn't report a problem with it. But I'm still going with my theory that it's a case of repo corruption, so I won't look into it any deeper.

**Comment by eMPee584** [comment]
In a sudden twist of chance, this problem occurs with the systemd repository, commit `e1ea4e5f1c429fbe62e76fc5b42bee32c2dcd770`.
Guess it's by design?

**Comment by mhagger** [comment]
@eMPee584: that's helpful! The problem (at least in the case of the systemd repo) is that it includes annotated tags without messages, and that was confusing the object-parsing code. Empirically it looks like Git also tolerates commits without commit messages. I'll fix both of those cases shortly.
