### ISSUE TITLE
Add "Level of concern" to the json output

### ISSUE THREAD

**Issue by dimapasko** [github/git-sizer#43]
It would be nice to have "Level of concern" column content in JSON output for more friendly automation.

We are going to write a script that will iterate across all our repos and will show all major Level of concerns. 
In this case, we need to run ```git-sizer``` several times, first, one to get "Level of concern" and second to get data from JSON.

What do you think?

**Comment by mhagger** [comment]
I think it is a good idea. Would you like to try writing a PR?

By the way, the level of concern is currently just the measured value divided by [the hard-coded values here](https://github.com/github/git-sizer/blob/087b40a9f72046f9b70ebae779eefcbd51ab3b56/sizes/output.go#L330-L401). So it wouldn't be too hard to compute the level of concern in whatever program is reading the JSON, which would even allow you to adjust the level of concern easily to align with the needs of your organization.

**Comment by mhagger** [comment]
There is no an improved JSON output, available if you use `--json-version=2`, which includes the level of concern.
