### ISSUE TITLE
"git count-objects" return way smaller size than git-sizer

### ISSUE THREAD

**Issue by mronnlun** [github/git-sizer#54]
Git-sizer returns the output at the bottom and states that we have 13.9GB of blobs. The .git folder is only 210MB and when running 

> git count-objects -vH

I also get 

> C:\Code\TestRepo>git count-objects -vH
count: 0
size: 0 bytes
in-pack: 554928
packs: 1
size-pack: 210.25 MiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes

What am I missing?

> C:\Code\TestRepo\>git-sizer.exe --verbose
Processing blobs: 159789
Processing trees: 356816
Processing commits: 38323
Matching commits to trees: 38323
Processing annotated tags: 0
Processing references: 3
| Name                         | Value     | Level of concern               |
| ---------------------------- | --------- | ------------------------------ |
| Overall repository size      |           |                                |
| * Commits                    |           |                                |
|   * Count                    |  38.3 k   |                                |
|   * Total size               |  12.0 MiB |                                |
| * Trees                      |           |                                |
|   * Count                    |   357 k   |                                |
|   * Total size               |   404 MiB |                                |
|   * Total tree entries       |  9.12 M   |                                |
| * Blobs                      |           |                                |
|   * Count                    |   160 k   |                                |
|   * Total size               |  13.7 GiB | *                              |
| * Annotated tags             |           |                                |
|   * Count                    |     0     |                                |
| * References                 |           |                                |
|   * Count                    |     3     |                                |
|                              |           |                                |
| Biggest objects              |           |                                |
| * Commits                    |           |                                |
|   * Maximum size         [1] |  1.71 KiB |                                |
|   * Maximum parents      [2] |     2     |                                |
| * Trees                      |           |                                |
|   * Maximum entries      [3] |  1.18 k   | *                              |
| * Blobs                      |           |                                |
|   * Maximum size         [4] |  7.82 MiB |                                |
|                              |           |                                |
| History structure            |           |                                |
| * Maximum history depth      |  38.3 k   |                                |
| * Maximum tag depth          |     0     |                                |
|                              |           |                                |
| Biggest checkouts            |           |                                |
| * Number of directories  [5] |  5.12 k   | **                             |
| * Maximum path depth     [6] |    13     | *                              |
| * Maximum path length    [7] |   219 B   | **                             |
| * Number of files        [6] |  34.9 k   |                                |
| * Total size of files    [6] |   490 MiB |                                |
| * Number of symlinks         |     0     |                                |
| * Number of submodules       |     0     |                                |

**Comment by mhagger** [comment]
`git count-objects` only counts "loose" objects; i.e., objects that are stored individually in files named like `.git/objects/ff/dd3fefe090a960f4dbb5a964795e0cbe56e651`. It *doesn't* count objects that are "packed" together in packfiles, those files named like `.git/objects/pack/pack-c492a51372e06c0a61a3622e1dec56a46761596b.pack`.

`git sizer` counts both (it doesn't care whether objects are loose or packed).
