### ISSUE TITLE
How to use this tool in mac?

### ISSUE THREAD

**Issue by luisxiaomai** [github/git-sizer#59]
Is there any mac executable binary?

**Comment by gudmundur** [comment]
If you've got [Go](https://golang.org) installed, then a `go install github.com/github/git-sizer` should just do the trick. It should build and add a `git-sizer` binary to your `$GOPATH/bin` directory.

**Comment by luisxiaomai** [comment]
@gudmundur , I just installed it by go. But when I run it , it pops up below error:
<img width="919" alt="屏幕快照 2019-09-04 下午4 11 54" src="https://user-images.githubusercontent.com/6835229/64237392-dcb7f780-cf2e-11e9-87ac-2f17a946443d.png">

**Comment by luisxiaomai** [comment]
thanks @gudmundur

**Comment by mhagger** [comment]
There are also pre-compiled releases for macOS on [the releases page](https://github.com/github/git-sizer/releases).

**Comment by gudmundur** [comment]
Thanks for pointing that out @mhagger. I totally didn't think of looking there. 😮
