### ISSUE TITLE
Can Git Sizer be used to compute a size of a directory including its history?

### ISSUE THREAD

**Issue by TomasHubelbauer** [github/git-sizer#62]
I assume the answer to this question is no, based on the reading of the `-` command, but I wonder if there might be a way anyway or perhaps you could direct me to a different tool / a Git command which is able to achieve this? I have a repository with a directory which is big and I plan on purging its (and only its, not the rest of the repository) history, but I want to first check how large it really is including all of its history and how much this operation will save me. It would also be useful to compare how large all the top level directories including their history are as compared to one another.

**Comment by larsxschneider** [comment]
👋 as a quick and dirty solution I would just extract the sub directory into a new repo and then measure its size. You can use the ‘git sub tree’ command to do this and it should be fairly quick: https://stackoverflow.com/questions/359424/detach-move-subdirectory-into-separate-git-repository/17864475#17864475

**Comment by TomasHubelbauer** [comment]
That's a great idea, thank you! I think this will be sufficient, so I'll close this ticket now.
