### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by slgraff** [github/git-sizer#63]
I've installed the latest release, git-sizer-1.3.0-darwin-386.zip, on my new Mac running macOS Catalina. When I run it I get this error:

`-bash: /usr/local/bin/git-sizer: Bad CPU type in executable`

The same error also occurs on a brand-new one-day-old MacBook Pro as well.

Is this perhaps an issue where macOS Catalina is no longer compatible with 32-bit apps?

**Comment by nschonni** [comment]
I would think you need to use git-sizer-1.3.0-darwin-amd64.zip

**Comment by larsxschneider** [comment]
@slgraff Alternatively you could install it via [brew](https://brew.sh/), a popular package manager for macOS, like this:
```
$ brew install git-sizer
```

**Comment by slgraff** [comment]
Thank you @larsxschneider , installing via Homebrew worked great. Closing.
