### ISSUE TITLE
For large repos, why is maxCheckoutBlobSize.value == uniqueBlobSize.value ?

### ISSUE THREAD

**Issue by impredicative** [github/git-sizer#65]
For large repos with binary blobs, I always found that `maxCheckoutBlobSize.value` == `uniqueBlobSize.value`. **How is it that they're always equal for such repos?** Note that I'm not necessarily using GitHub with such repos. An example is:

```bash
$ git-sizer --json --json-version 2 | egrep -A2 'maxCheckoutBlobSize|uniqueBlobSize'
Processing blobs: 5527                        
Processing trees: 32                        
Processing commits: 10                        
Matching commits to trees: 10                        
Processing annotated tags: 0                        
Processing references: 2                        
    "maxCheckoutBlobSize": {
        "description": "The maximum sum of file sizes in any checkout",
        "value": 3976127840,
--
    "uniqueBlobSize": {
        "description": "The total size of all distinct blob objects",
        "value": 3976127840,

```

For small repos, there was always a meaningful difference, with `uniqueBlobSize.value` being larger. An example is:
```
$ git-sizer --json --json-version 2 | egrep -A2 'maxCheckoutBlobSize|uniqueBlobSize'
Processing blobs: 1653                        
Processing trees: 3481                        
Processing commits: 1630                        
Matching commits to trees: 1630                        
Processing annotated tags: 0                        
Processing references: 5                        
    "maxCheckoutBlobSize": {
        "description": "The maximum sum of file sizes in any checkout",
        "value": 165999,
--
    "uniqueBlobSize": {
        "description": "The total size of all distinct blob objects",
        "value": 85867069,
```

**Comment by mhagger** [comment]
That seems strange. It's easy to image scenarios where these two values would in fact be equal (for example, a repo with a single commit or a repo where files only get added over time, never modified or deleted). But it does seem unexpected if you are talking about "normal" repositories. Can you find / share an example repository that I can use to reproduce this myself? (I just ran `git-sizer` against a random large repo and the values were _not_ the same.)

**Comment by impredicative** [comment]
Indeed it could have been because files were never modified or deleted. I will close this issue until I have a counterexample to show.
