### ISSUE TITLE
Please update to Go 1.16 and also release for macOS ARM64

### ISSUE THREAD

**Issue by dbast** [github/git-sizer#68]
Go 1.16 was just released with macOS ARM64 support, see https://blog.golang.org/go1.16

**Comment by dbast** [comment]
Regarding signing and darwin_arm64 binaries ... go 1.16 automatically adds an add hoc signature, see the comment here https://github.com/git-lfs/git-lfs/issues/4403

**Comment by mhagger** [comment]
I'd like to wait for a 1.16.1 before switching over, to give some time for any problems in the 1.16 series to get ironed out. It should be pretty easy to build this yourself if you want to do any testing before then.

**Comment by dbast** [comment]
Go 1.16.2 is out https://golang.org/doc/devel/release.html#go1.16.minor :)

**Comment by mhagger** [comment]
@dbast: This is implemented by #73. Would you be able to test that (the installation of the vendored Go toolchain, the build, and that the executable works)? I don't have that OS let alone that hardware version.
