### ISSUE TITLE
Release 1.4.0 Windows builds flagged as malicious by multiple vendors

### ISSUE THREAD

**Issue by coldacid** [github/git-sizer#78]
git-sizer.exe in both git-sizer-1.4.0-windows-386.zip and git-sizer-1.4.0-windows-amd64.zip, along with the zip files themselves, are flagged as malicious by multiple vendors, per VirusTotal.

* git-sizer-1.4.0-windows-386.zip: [3D72CF32D30B82C5C76E560C702C41E50CB03710451DC1764097C64CECF3ED22](https://www.virustotal.com/gui/file/3d72cf32d30b82c5c76e560c702c41e50cb03710451dc1764097c64cecf3ed22/detection)
* git-sizer-1.4.0-windows-amd64.zip: [D37945EC6E253281ADADCBBD358DA00E0FBFB4A099700A2A58E320EC1C2EDCA4](https://www.virustotal.com/gui/file/d37945ec6e253281adadcbbd358da00e0fbfb4a099700a2a58e320ec1c2edca4/detection)
* git-sizer.exe x86: [73C65704CF54FD79314C22534641605694E3314BEAE69824DBCFEE818FD663C1](https://www.virustotal.com/gui/file/73c65704cf54fd79314c22534641605694e3314beae69824dbcfee818fd663c1/detection)
* git-sizer.exe amd64: [2A591C604177FC7D79A4097A5B76B4247CE6A11D9FAAC880C3DB6CD79924CC4D](https://www.virustotal.com/gui/file/2a591c604177fc7d79a4097a5b76b4247ce6a11d9faac880c3db6cd79924cc4d/detection)

**Comment by mhagger** [comment]
Sorry for the delay getting back to you. I have reproduced the build artifacts, byte-for-byte, in a clean environment, with a freshly downloaded and verified Go toolchain. So there was no contamination of the build environment.

`git-sizer` has only two external runtime (as opposed to test-time) dependencies:

* `github.com/cli/safeexec` — a trivial package, also maintained by GitHub. I just audited it and it doesn't do anything untoward. On Windows it _does_ search the directories in `PATH` manually to try to find the `git` executable, which could conceivably be considered suspicious behavior by an automated tool (?). (Ironically, it does this to prevent a possible social-engineering attack.)
* `github.com/spf13/pflag` — a very commonly used package. I don't know of any reports of security problems with it.

So I'm confident that these are false positives.

I don't expect to have time to work to correct these apparently mistaken reports, so I will close this issue. If somebody else wants to take up that task, feel free to reopen it.

**Comment by coldacid** [comment]
Based on your analysis I'm reporting git-sizer.exe detections as a false positive.

**Comment by mhagger** [comment]
Thanks, @coldacid! :sparkles:
