### ISSUE TITLE
Detect & report tmp_pack files

### ISSUE THREAD

**Issue by katrinleinweber** [github/git-sizer#80]
When `git repack` fails, it's possible that `.git/objects/pack/tmp_pack_*` files are left over. Since these are likely to be large, I suggest that git-sizer users could benefit from being informed about them, for example in the _Biggest objects_ section.

**Comment by mhagger** [comment]
Thanks for the idea. Until now, `git-sizer` has only concerned itself with the _logical_ structure of the repository, independent of how things are packed or the presence of unreachable objects, let alone things like temp files that may have been left behind by interrupted processes. Even though there have been requests to broaden `git-sizer`'s scope, I think that it is better to keep its mission focused, and let other tools concern themselves with other types of repository on-disk problems, like cruft files. (This might arguably even be a nice feature to add to `git fsck`.)

So I will close this issue. If we decide to expand `git-sizer`'s scope, we can always re-open it.
