### ISSUE TITLE
Impove NewObjectIter method

### ISSUE THREAD

**Issue by Cactusinhand** [github/git-sizer#95]
Hi  @mhagger 

To get all objects in git repo, I wonder if `git cat-file --batch-check='%(objectname) %(objecttype) %(objectsize)' --batch-all-objects ` is more effective and easier than `git rev-list --objects --stdin` && `git cat-file --batch-check --buffer`.

**Comment by mhagger** [comment]
@Cactusinhand: Thanks for the suggestion. Indeed, `--batch-all-objects` is a fast way to enumerate all objects. But `git-sizer` (a) only wants to process reachable objects, and (b) depends critically on objects being returned in "parent-to-child" order. I don't think that `--batch-all-objects` has either of those properties. So I don't think that this would be easy to change.

**Comment by Cactusinhand** [comment]
> @Cactusinhand: Thanks for the suggestion. Indeed, `--batch-all-objects` is a fast way to enumerate all objects. But `git-sizer` (a) only wants to process reachable objects, and (b) depends critically on objects being returned in "parent-to-child" order. I don't think that `--batch-all-objects` has either of those properties. So I don't think that this would be easy to change.

Oh, I get it. Thanks for your reply.
