### ISSUE TITLE
git-sizer error: "running 'git config': exit status 129"

### ISSUE THREAD

**Issue by pippim** [github/git-sizer#97]
Not sure what the problem is. Downloaded zip file for Linux AMD 64 but get above error using:

``` terminal
$ git-sizer

error: running 'git config': exit status 129
```

It appears that `git config` has an invalid parameter but it is called by the `git-sizer` command which theoretically knows how to call the `git` command with the correct parameters?

If it helps:

``` terminal
$ type -a git
git is /usr/bin/git

$ type -a git-sizer
git-sizer is /home/rick/bin/git-sizer

$ git-sizer --version
git-sizer release 1.5.0

$ git --version
git version 2.7.4
```

Any suggestions would be appreciated as it would be nice to know how much GitHub resources my repo is consuming.

**Comment by lastikas** [comment]
I had the same problem running on Ubuntu 18.04.6 and git-sizer 1.5.0

git-sizer 1.4.0 works just fine

**Comment by Cactusinhand** [comment]
Hello, @pippim, my suggestion is to upgrade your Git, and have a try again.

**Comment by Cactusinhand** [comment]
@mhagger  Apparently, to fix this issue, client Git should upgrade to a newer version, and README should update too.

**Comment by pippim** [comment]
@Cactusinhand in Ubuntu-land, the folks at Canonical will **sloowwwllllyyyy** upgrade to the latest Git client version. Another Ubuntu user @lastikas suggested above that downgrading to Git version `1.4` will also work. It would be nice to have a "patch" for the error message in the current version `1.5` but I can wait until it eventually works in Ubuntu.

**Comment by adam-azarchs** [comment]
If you're using ubuntu you can always use the [git ppa](https://launchpad.net/~git-core/+archive/ubuntu/ppa) to get an up to date version:
```
sudo add-apt-repository ppa:git-core/ppa
sudo apt update
sudo apt upgrade
```

**Comment by mhagger** [comment]
I think that #105 should fix this problem, by avoiding the use of the newer `git config` features. Please let me know if it works for you! (For now you'll have to install and build it yourselves if you want to test it.)
